INSERT INTO `items` (`name`, `label`, `weight`) VALUES
  ('burger', 'Hamburger', 1),
  ('chaser', 'Chaser Choco Bar', 1),
  ('meteorite', 'Meteorite Choco Bar', 1),
  ('hotdog', 'Hotdog', 1),
  ('taco', 'Taco', 1),
  ('piswasser', 'Pißwasser', 1),
  ('mount_whisky', 'The Mount Whisky', 1),
  ('tequila', 'Tequilya', 1),
  ('nogo_vodka', 'Nogo Vodka', 1),
  ('raine', 'Raine Water', 1),
  ('bean_machine_coffe', 'Bean Machine Coffe', 1),
  ('sprunk', 'Sprunk', 1),
  ('cola', 'Cola', 1),
  ('shot_mount_whisky', 'Shot Mount Whisky', 1),
  ('shot_nogo_vodka', 'Shot Nogo Vodka', 1),
  ('shot_tequila', 'Shot Tequilya', 1),
  ('costa_del_perro', 'Costa Del Perro', 1),
  ('rockford_hill', 'Rockford Hill Reserve', 1),
  ('vinewood_red', 'Vinewood Red Zinfadel', 1),
  ('vinewood_blanc', 'Vinewood Sauvignon Blanc', 1),
  ('glass_costa_del_perro', 'Glass Costa Del Perro', 1),
  ('glass_rockford_hill', 'Glass Rockford Hill Reserve', 1),
  ('glass_vinewood_red', 'Glass  Vinewood Red Zinfadel', 1),
  ('glass_vinewood_blanc', 'Glass Vinewood Sauvignon Blanc', 1)
;